[package]
name = "shut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
exitcode = "1.1.2"
netstat2 = "0.9"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
heim = {version = "0.1.0-rc.1", default-features = false, features = ["process"]}
